name: bitcoinz_wallet_desktop
description: "BitcoinZ Desktop Wallet - A secure, privacy-focused desktop wallet for BitcoinZ cryptocurrency built with Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.1
  
  # Secure storage for desktop
  flutter_secure_storage: ^9.0.0
  
  # Desktop-specific packages
  window_manager: ^0.3.7
  system_tray: ^2.0.3
  launch_at_startup: ^0.2.2
  
  # File operations
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  
  # FFI for Rust integration
  ffi: ^2.1.0
  
  # HTTP requests
  http: ^1.1.0
  
  # JSON handling
  json_annotation: ^4.8.1
  
  # UI and utilities
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  
  # QR Code
  qr_flutter: ^4.1.0
  
  # Crypto utilities
  crypto: ^3.0.3
  
  # BIP39 for seed phrase validation
  bip39: ^1.0.6
  
  # Number formatting
  intl: ^0.18.1
  
  # Logging
  logger: ^2.0.2
  
  # Desktop UI enhancements
  bitsdojo_window: ^0.1.6
  desktop_context_menu: ^0.1.0
  hotkey_manager: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
