# AppImage configuration
display_name: BitcoinZ Black Amber
icon: assets/app_icon/app_icon.png
generic_name: BitcoinZ Wallet
categories:
  - Finance
  - Network
startup_notify: true
# Removed actions field to fix flutter_distributor compatibility issue
# actions:
#   - name: New Window
#     label: Open New Window
prebuild_scripts:
  - bash linux/packaging/pre_build.sh